import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const distDir = path.join(root, "frontend", "dist");
const outFile = path.join(root, "google", "kys-app", "Index.html");

const indexPath = path.join(distDir, "index.html");
if (!fs.existsSync(indexPath)) {
  console.error("Run vite build first (npm run build from frontend).");
  process.exit(1);
}

let html = fs.readFileSync(indexPath, "utf8");

function inlineAsset(match, attr, relPath) {
  const filePath = path.join(distDir, relPath.replace(/^\.\//, ""));
  if (!fs.existsSync(filePath)) return match;
  const content = fs.readFileSync(filePath, "utf8");
  if (attr === "script") {
    return `<script type="module">\n${content}\n</script>`;
  }
  return `<style>\n${content}\n</style>`;
}

html = html.replace(/<script[^>]+src="([^"]+)"[^>]*><\/script>/, (m, src) => inlineAsset(m, "script", src));
html = html.replace(/<link[^>]+href="([^"]+\.css)"[^>]*>/, (m, href) => inlineAsset(m, "style", href));

html = html.replace("<head>", '<head>\n    <base target="_top" />');

const banner = "<!-- Generated by npm run build — do not edit by hand -->\n";
fs.writeFileSync(outFile, banner + html);
console.log("Wrote", outFile);
